snappmusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls", namespace="users")),
    path('institute/', include("institute.urls", namespace="institute")),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name=views.Home.name),
    path('login/', views.Login.as_view(), name=views.Login.name),
    path('register/', views.UserRegister.as_view(), name=views.UserRegister.name),
    path('<int:pk>/', views.ViewInstitute.as_view(), name=views.ViewInstitute.name),
    path('class/<int:pk>', views.ViewClass.as_view(), name=views.ViewClass.name),
    path('class/register', views.RegisterClass.as_view(), name=views.RegisterClass.name),
    path('logout/', views.Logout, name="logout"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    full_name = models.CharField(max_length=120)
    phone = models.CharField(max_length=120, default=None, null=True)
    type = models.BooleanField(default=0)
    logo = models.ImageField(default=None, null=True, blank=True)
    description = models.TextField(max_length=1000, default="", null=True, blank=True)
    address = models.TextField(max_length=1000, default="", null=True, blank=True)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.username = self.username.lower()
        super(User, self).save(*args, **kwargs)


class InstitutionClass(models.Model):
    name = models.CharField(max_length=120, null=True, blank=True, default=None)
    logo = models.ImageField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    teacher = models.CharField(max_length=120, null=True, blank=True, default=None)
    instrument = models.CharField(max_length=120, null=True, blank=True, default=None)
    time = models.CharField(max_length=120, null=True, blank=True, default=None)

    def __str__(self):
        return self.name


class UserClass(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_class = models.ForeignKey(InstitutionClass, on_delete=models.CASCADE)


class InstituteComment(models.Model):
    institute = models.ForeignKey(User, on_delete=models.CASCADE, related_name="institute")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    comment = models.CharField(max_length=120, null=True, blank=True, default=None)
    rate = models.IntegerField(default=5)

institute/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib import messages
from institute.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from institute import forms
from users.models import User, InstitutionClass, UserClass


# Create your views here.

class Home(LoginRequiredMixin, View):
    name = "Home"
    template_name = "institute/home.html"

    def get(self, request):
        classes = InstitutionClass.objects.filter(user__username=request.user)
        context = {
            'classes': classes
        }
        return render(request, self.template_name, context)


class AddClass(LoginRequiredMixin, View):
    name = "AddClass"
    form = forms.AddInstituteClassForm
    template_name = "institute/add_class.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        user = User.objects.get(username=request.user)
        updated_request = request.POST.copy()
        updated_request.update({"user": user.id})
        post_form = self.form(updated_request, request.FILES)
        if post_form.is_valid():
            post_form.save()
        else:
            messages.error(request, "مشکلی پیش آمده است.")
            return render(request, self.template_name)
        messages.success(request, "کلاس با موفقیت اضافه شد")
        return redirect("institute:Home")


class EditClass(LoginRequiredMixin, UpdateView):
    model = InstitutionClass
    name = "EditClass"
    form_class = forms.EditInstituteClassForm
    template_name = "institute/edit_class.html"
    success_url = '/institute/'
    context_object_name = "class"


class DeleteClass(LoginRequiredMixin, DeleteView):
    model = InstitutionClass
    name = "DeleteClass"
    success_url = '/institute/'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class InstituteRegister(View):
    name = "InstituteRegister"
    template_name = "institute/institute_register.html"
    form = forms.RegisterInstitute

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        post_form = self.form(request.POST, request.FILES)
        if post_form.is_valid():
            password = request.POST.get("password")
            if password != post_form.cleaned_data.get("password_2"):
                messages.error(request, "رمز عبور با تکرار رمز عبور همخوانی ندارد.")
                return render(request, self.template_name)
            else:
                post_form.save()
                user = User.objects.get(username=post_form.cleaned_data.get('username'))
                user.set_password(password)
                user.save()
                login(request, user)
                messages.success(request, "اکانت شما با موفقیت ایجاد شد.")
                return redirect('institute:Home')
        else:
            print(post_form.errors)
            messages.error(request, "نام کاربری دیگری با این نام وجود دارد.")
        return render(request, self.template_name)


class InstituteClassUsers(LoginRequiredMixin, View):
    name = "InstituteClassUsers"
    template_name = "institute/institute_users.html"

    def get(self, request):
        institute_classes = InstitutionClass.objects.filter(user__username=request.user)
        users_classes = list()
        for institute_class in institute_classes:
            users = UserClass.objects.filter(user_class=institute_class)
            for usr in users:
                _dict = {
                    "username": usr.user.username,
                    "class_name": institute_class.name,
                    "class_teacher": institute_class.teacher,
                    "class_time": institute_class.time,
                }
                users_classes.append(_dict)
        context = {
            "user_classes": users_classes
        }
        return render(request, self.template_name, context)


def Logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('users:login')
    else:
        return redirect('users:login')

users/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from users.models import User, InstitutionClass, UserClass


# Create your views here.

class Home(View):
    name = "home"

    def get(self, request):
        institutes = User.objects.filter(type=1)
        context = {
            "institutes": institutes,
        }
        return render(request, "users/home.html", context)


class ViewInstitute(View):
    name = "ViewInstitute"
    template_name = "users/user_institute_view.html"

    def get(self, request, pk):
        institute = User.objects.get(type=1, id=pk)
        classes = InstitutionClass.objects.filter(user=institute)
        context = {
            "institute": institute,
            "classes": classes,
        }
        return render(request, self.template_name, context)


class ViewClass(View):
    name = "ViewClass"
    template_name = "users/user_institute_class.html"

    def get(self, request, pk):
        class_obj = InstitutionClass.objects.get(id=pk)
        if request.user.id is not None:
            if request.user.type == 1:
                is_register = -1
            else:
                user_classes = UserClass.objects.filter(user__username=request.user, user_class=class_obj)
                print(user_classes)
                if len(user_classes) > 0:
                    is_register = 1
                else:
                    is_register = 0
        else:
            is_register = 0
        context = {
            "class": class_obj,
            "is_register": is_register,
        }
        return render(request, self.template_name, context)


class RegisterClass(View):
    name = "RegisterClass"

    def post(self, request):
        if request.user.id is None:
            messages.error(request, "برای ثبت نام در کلاس باید وارد حساب کاربری خود بشوید و یا ثبت نام کنید")
            return redirect("users:login")

        class_id = request.POST.get("class_id")
        try:
            class_obj = InstitutionClass.objects.get(id=class_id)
            user_obj = User.objects.get(id=request.user.id, type=0)
        except Exception as e:
            messages.error(request, "همچین اکانت و یا کلاسی در دسترس نمیباشد")
            return redirect("users:ViewClass", class_id)
        user_class = UserClass.objects.create(user=user_obj, user_class=class_obj)
        user_class.save()
        messages.success(request, "درخواست شما با موفقیت ثبت شد")
        return redirect("users:ViewClass", class_id)


class Login(View):
    name = 'login'
    template_name = "users/login.html"

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            if user.type == 0:
                return redirect('users:home')
            else:
                return redirect("institute:Home")
        else:
            messages.error(request, 'نام کاربری یا گذرواژه اشتباه میباشد.')
            return redirect('users:login')

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, self.template_name)
        else:
            if request.user.type == 0:
                return redirect('users:home')
            else:
                return redirect("institute:Home")


class UserRegister(View):
    name = "UserRegister"
    template_name = "users/user_register.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get("username")
        phone = request.POST.get("phone")
        full_name = request.POST.get("full_name")
        password = request.POST.get("password")
        password_2 = request.POST.get("password_2")
        if password != password_2:
            messages.error(request, "رمز عبور با تکرار رمز عبور همخوانی ندارد.")
            return render(request, self.template_name)
        else:
            check_user = User.objects.filter(username=username).count()
            if check_user != 0:
                messages.error(request, "نام کاربری دیگری با این نام کاربری وجود دارد.")
                return render(request, self.template_name)
            else:
                user = User.objects.create(username=username, phone=phone, full_name=full_name, type=0)
                user.set_password(password)
                user.save()
                login(request, user)
                messages.success(request, "اکانت شما با موفقیت ایجاد شد.")
                return redirect('users:home')


def Logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('users:login')
    else:
        return redirect('users:login')

users/templates/users/home.html
{% extends 'index.html' %}
{% load static %}
{% block css %}
    <style>
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
            grid-gap: 20px;
            align-items: stretch;
        }

        .grid > article {
            border: 1px solid #ccc;
            box-shadow: 2px 2px 6px 0px rgba(0, 0, 0, 0.3);
        }

        .grid > article img {
            width: 100%;
            object-fit: contain;
            min-height: 220px;
            padding-right: 2%;
            padding-left: 2%;
            padding-top: 2%;
        }

        .grid .text {
            padding: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                خانه
            </h1>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box box-success">
                            <div class="box-body with-border" id="canvas_div">
                                {% include 'messages.html' %}
                                {% include 'users/user_institute_post.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- datepicker -->


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}
<!-- datepicker -->

users/templates/users/login.html
{% extends 'login_base.html' %}
{% load static %}

{% block title %}
    <title>پنل | ورود</title>
{% endblock %}


{% block body %}
    <div class="div_form row" style="margin-top: 5%">

        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <img src="{% static 'dist/img/znu_logo.jpg' %}" alt="User Image"
                 style="height: 190px!important; text-align: center; position: relative; margin:20px;">
            <h4>SnappMusic</h4>
            <input class="name" type="text" name="username" placeholder="نام کاربری را وارد نمایید">
            <input class="pw" type="password" name="password" placeholder="پسورد را وارد نمایید"/>
            <div class="col-md-12">

                <div class=" col-md-6 ">
                    <a href="{% url "users:UserRegister" %}" >
                        <span class="register_button" >یا ثبت نام کنید</span>
                    </a>
                </div>
                <div class="col-md-6">
                    <input class="login_button" type="submit" value="ورود" style="margin-left: 31%"/>
                </div>
            </div>

        </form>


    </div>
    <!-- jQuery 3 -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% endblock %}

users/templates/users/user_institute_class.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_1" data-toggle="tab">توضیحات کلاس</a></li>
                        </ul>
                        {% include "messages.html" %}

                        <div class="tab-content">
                            <div class="tab-pane active" id="tab_1">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="box box-info box-solid">
                                            <div class="box-header with-border">
                                                <h3 class="box-title">توضیحات کلاس {{ class.name }}</h3>
                                                <!-- /.box-tools -->
                                            </div>
                                            <!-- /.box-header -->
                                            <div class="box-body">
                                                <div class="row">
                                                    <div class="col-md-6 col-xs-6">
                                                        <div class="container">
                                                            <div class="col-md-6">
                                                                <img src="{{ class.logo.url }}" alt="No photo"
                                                                     style="max-width: 98%;padding-right: 2%;padding-top: 2%;">

                                                            </div>
                                                            <div class="col-md-6">
                                                                <h4>نام آموزشگاه: <a
                                                                        href="{% url "users:ViewInstitute" class.user.id %}">{{ class.user.full_name }}</a>
                                                                </h4>


                                                                <h4>نام استاد: {{ class.teacher }}</h4>
                                                                <h4>ساز: {{ class.instrument }}</h4>
                                                                <h4>ساعت برگزاری کلاس: {{ class.time }}</h4>
                                                                <br><br>
                                                                {% if is_register == 1 %}
                                                                    <button class="btn btn-info" disabled>شما قبلا در
                                                                        این کلاس ثبت نام کرده اید.
                                                                    </button>
                                                                {% elif is_register == -1 %}
                                                                    <button class="btn btn-warning" disabled>
                                                                        شما قادر به ثبت نام در این کلاس نیستید
                                                                    </button>
                                                                {% else %}
                                                                    <form method="post"
                                                                          action="{% url "users:RegisterClass" %}">
                                                                        {% csrf_token %}
                                                                        <input type="text" style="display: none;"
                                                                               value="{{ class.id }}" name="class_id">
                                                                        <input type="submit" value="ثبت نام"
                                                                               class="btn btn-success">
                                                                    </form>
                                                                {% endif %}

                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>
                                            <!-- /.box-body -->
                                        </div>
                                        <!-- /.box -->
                                    </div>

                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- datepicker -->


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}
<!-- datepicker -->

users/templates/users/user_institute_class_tab.html
<div class="container">
    <main class="grid">
        {% for class in classes %}
            <article>
                <img src="{{ class.logo.url }}" alt="Photo">
                <div class="text row">
                    <h3>{{ class.name }}</h3>
                    <p>{{ class.teacher }}</p>
                    <p>{{ class.time }}</p>

                    <a href="{% url "users:ViewClass" class.id %}" class="btn btn-primary btn-block align-self-end">توضیحات</a>

                </div>

            </article>
        {% endfor %}
    </main>
</div>

users/templates/users/user_institute_info_tab.html
<div class="container">
    <div class="col-md-6">
        <img src="{{ institute.logo.url }}" alt="No photo" style="max-width: 98%;padding-right: 2%;padding-top: 2%;">

    </div>
    <div class="col-md-6">
        <h4>معرفی آموزشگاه:</h4>
        <p>{{ institute.description }}</p>
        <h4>آدرس:</h4>
        <p>{{ institute.address }}</p>
        <h4>شماره تلفن:</h4>
        <p>{{ institute.phone }}</p>

    </div>
</div>

users/templates/users/user_institute_post.html
<div class="container">
    <main class="grid">
        {% for institute in institutes %}
            <article>
                <img src="{{ institute.logo.url }}" alt="Photo">
                <div class="text row">
                    <h3>{{ institute.full_name }}</h3>
                    <p class="text">{{ institute.description }}</p>

                        <a href="{% url "users:ViewInstitute" institute.id %}"
                           class="btn btn-primary btn-block align-self-end">معرفی بیشتر</a>
                </div>

            </article>
        {% endfor %}
    </main>
</div>

users/templates/users/user_institute_view.html
{% extends 'index.html' %}
{% load static %}
{% block css %}
    <style>
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            grid-gap: 20px;
            align-items: stretch;
        }

        .grid > article {
            border: 1px solid #ccc;
            box-shadow: 2px 2px 6px 0px rgba(0, 0, 0, 0.3);
        }

        .grid > article img {
            width: 100%;
            object-fit: contain;
            min-height: 220px;
            padding-right: 2%;
            padding-left: 2%;
            padding-top: 2%;
        }

        .grid .text {
            padding: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    {% include 'users/user_institute_view_info.html' %}
                </div>
            </div>
        </section>

    </div>


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}

users/templates/users/user_institute_view_info.html
<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab">توضیحات</a></li>
        <li><a href="#tab_2" data-toggle="tab">کلاس ها</a></li>

    </ul>
    <div class="tab-content">

        <div class="tab-pane active" id="tab_1">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">توضیحات آموزشگاه {{ institute.full_name  }}</h3>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6 col-xs-6">
                                    {% include "users/user_institute_info_tab.html" %}
                                </div>

                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>

            </div>
        </div>
        <div class="tab-pane" id="tab_2">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">کلاس های آموزشگاه {{ institute.full_name  }}</h3>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6 col-xs-6">
                                    {% include 'users/user_institute_class_tab.html' %}
                                </div>

                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>

            </div>
        </div>
    </div>


</div>

users/templates/users/user_register.html
{% extends 'login_base.html' %}
{% load static %}

{% block title %}
    <title>پنل | ثبت نام</title>
{% endblock %}


{% block body %}
    <div class="row div_form" style="margin-top: 1%">

        <form action="{% url 'users:UserRegister' %}" method="post">
            {% csrf_token %}
            <img src="{% static 'dist/img/znu_logo.jpg' %}" alt="User Image"
                 style="height: 190px!important; text-align: center; position: relative; margin:20px;">
            <h4>SnappMusic</h4>
            <label style="float: right" for="">
                نام کاربری:
            </label>
            <input type="text" name="username" placeholder="نام کاربری  خودرا وارد نمایید" id="username" required/>
            <label style="float: right" for="">
                نام و نام خانودگی:
            </label>
            <input type="text" name="full_name" placeholder="نام و نام خانوادگی خود را وارد نمایید" id="full_name"
                   required/>
            <label style="float: right" for="">
                شماره تماس:
            </label>
            <input type="text" name="phone" placeholder="شماره تماس خود را وارد نمایید" id="phone" required/>
            <label style="float: right" for="">
                رمز عبور:
            </label>
            <input type="password" name="password" placeholder="رمز عبور خود را وارد نمایید" id="password" required/>
            <label style="float: right" for="">
                تکرار رمز عبور:
            </label>
            <input type="password" name="password_2" placeholder="تکرار رمز عبور خود را وارد نمایید" id="password_2"
                   required/>
            {#            <input class="register_btn" type="submit" value="ثبت نام" style="margin-left: 31%"/>#}
            {#                        <div class="col-md-12">#}

            <div class=" col-md-6 ">
                <a href="{% url "institute:InstituteRegister" %}">
                    <span class="register_button">ثبت نام آموزشگاه</span>
                </a>
            </div>
            <div class="col-md-6">
                <input class="login_button" type="submit" value="ثبت نام" style="margin-left: 31%"/>
            </div>

        </form>
    </div>
    <!-- jQuery 3 -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% endblock %}