snappmusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls", namespace="users")),
    path('institute/', include("institute.urls", namespace="institute")),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name=views.Home.name),
    path('login/', views.Login.as_view(), name=views.Login.name),
    path('register/', views.UserRegister.as_view(), name=views.UserRegister.name),
    path('<int:pk>/', views.ViewInstitute.as_view(), name=views.ViewInstitute.name),
    path('class/<int:pk>', views.ViewClass.as_view(), name=views.ViewClass.name),
    path('class/register', views.RegisterClass.as_view(), name=views.RegisterClass.name),
    path('logout/', views.Logout, name="logout"),

]

institute/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib import messages
from institute.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from institute import forms
from users.models import User, InstitutionClass, UserClass


# Create your views here.

class Home(LoginRequiredMixin, View):
    name = "Home"
    template_name = "institute/home.html"

    def get(self, request):
        classes = InstitutionClass.objects.filter(user__username=request.user)
        context = {
            'classes': classes
        }
        return render(request, self.template_name, context)


class AddClass(LoginRequiredMixin, View):
    name = "AddClass"
    form = forms.AddInstituteClassForm
    template_name = "institute/add_class.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        user = User.objects.get(username=request.user)
        updated_request = request.POST.copy()
        updated_request.update({"user": user.id})
        post_form = self.form(updated_request, request.FILES)
        if post_form.is_valid():
            post_form.save()
        else:
            messages.error(request, "مشکلی پیش آمده است.")
            return render(request, self.template_name)
        messages.success(request, "کلاس با موفقیت اضافه شد")
        return redirect("institute:Home")


class EditClass(LoginRequiredMixin, UpdateView):
    model = InstitutionClass
    name = "EditClass"
    form_class = forms.EditInstituteClassForm
    template_name = "institute/edit_class.html"
    success_url = '/institute/'
    context_object_name = "class"


class DeleteClass(LoginRequiredMixin, DeleteView):
    model = InstitutionClass
    name = "DeleteClass"
    success_url = '/institute/'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class InstituteRegister(View):
    name = "InstituteRegister"
    template_name = "institute/institute_register.html"
    form = forms.RegisterInstitute

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        post_form = self.form(request.POST, request.FILES)
        if post_form.is_valid():
            password = request.POST.get("password")
            if password != post_form.cleaned_data.get("password_2"):
                messages.error(request, "رمز عبور با تکرار رمز عبور همخوانی ندارد.")
                return render(request, self.template_name)
            else:
                post_form.save()
                user = User.objects.get(username=post_form.cleaned_data.get('username'))
                user.set_password(password)
                user.save()
                login(request, user)
                messages.success(request, "اکانت شما با موفقیت ایجاد شد.")
                return redirect('institute:Home')
        else:
            print(post_form.errors)
            messages.error(request, "نام کاربری دیگری با این نام وجود دارد.")
        return render(request, self.template_name)


class InstituteClassUsers(LoginRequiredMixin, View):
    name = "InstituteClassUsers"
    template_name = "institute/institute_users.html"

    def get(self, request):
        institute_classes = InstitutionClass.objects.filter(user__username=request.user)
        users_classes = list()
        for institute_class in institute_classes:
            users = UserClass.objects.filter(user_class=institute_class)
            for usr in users:
                _dict = {
                    "username": usr.user.username,
                    "class_name": institute_class.name,
                    "class_teacher": institute_class.teacher,
                    "class_time": institute_class.time,
                }
                users_classes.append(_dict)
        context = {
            "user_classes": users_classes
        }
        return render(request, self.template_name, context)


def Logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('users:login')
    else:
        return redirect('users:login')

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SnappMusic</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap-theme.css' %}">
    <!-- Bootstrap rtl -->
    <link rel="stylesheet" href="{% static 'dist/css/rtl.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

    <![endif]-->


    <!-- Google Font -->

    {% block css %}

    {% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><small>SMusic</small></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>SnappMusic</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top"><!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="user user-menu">
                        {% if request.user.id != None %}
                            <a href="#">
                                <span class="hidden-xs">{{ request.user }}</span>
                            </a>
                        {% else %}
                            <a href="{% url "users:login" %}" class="btn btn-warning">
                                <span class="hidden-xs">وارد حساب کاربری خود شوید.</span>
                            </a>
                        {% endif %}
                    </li>
                </ul>

            </div>
        </nav>
    </header>
    <!-- right side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-right image">
                    <img src="{% static 'dist/img/Music-CC.jpg' %}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-right info">
                    {% if request.user.id != None %}
                        <p style="text-align: center; margin-top: 2%; margin-right: 2%">{{ request.user }}</p>
                    {% endif %}
                </div>
            </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">منو</li>
                <li class="active"><a href="{% url "users:home" %}">
                    <i class="fa fa-home"></i> <span>خانه</span>
                    <span class="pull-left-container">
                  <i class="fa pull-left"></i>
                </span>
                </a>
                </li>
                <li class="active">
                    <a href="{% url 'users:logout' %}">
                        <i class="fa fa-sign-out"></i> <span>خروج</span>
                    </a>
                </li>


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
    {% block content %}

    {% endblock %}

    <footer class="main-footer text-left">
        <strong>Copyleft &copy; 2020 <a href="#">Zanjan University</a></strong>
    </footer>
</div>


<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<!-- InputMask -->
<script src="{% static 'plugins/input-mask/jquery.inputmask.js' %}"></script>
<script src="{% static 'plugins/input-mask/jquery.inputmask.date.extensions.js' %}"></script>
<script src="{% static 'plugins/input-mask/jquery.inputmask.extensions.js' %}"></script>
<!-- date-range-picker -->
<script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- bootstrap datepicker -->
<script src="{% static 'bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<!-- bootstrap color picker -->
<script src="{% static 'bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js' %}"></script>
<!-- bootstrap time picker -->
<script src="{% static 'plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>
<!-- SlimScroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- iCheck 1.0.1 -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static  'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static  'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static  'dist/js/demo.js' %}"></script>
<!-- babakhani datepicker -->
<script src="{% static  'dist/js/persian-date-0.1.8.min.js' %}"></script>
<script src="{% static  'dist/js/persian-datepicker-0.4.5.min.js' %}"></script>


{% block js %}

{% endblock %}


{% block script %}

{% endblock %}

</body>
</html>

templates/institute_index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SnappMusic</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap-theme.css' %}">
    <!-- Bootstrap rtl -->
    <link rel="stylesheet" href="{% static 'dist/css/rtl.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

    <![endif]-->


    <!-- Google Font -->

    {% block css %}

    {% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><small>SMusic</small></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>SnappMusic</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="user user-menu">
                        <a href="#" >
                            <img src="{{ request.user.logo.url }}" class="user-image">
                            <span class="hidden-xs">{{ request.user }}</span>
                        </a>

                    </li>
                </ul>

            </div>
        </nav>
    </header>
    <!-- right side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-right image">
                    <img {% if request.user.logo.url %} src="{{ request.user.logo.url }}" {% else %}
                                                        src="{% static 'dist/img/Music-CC.jpg' %}" {% endif %}
                                                        class="img-circle" alt="No Image">
                </div>
                <div class="pull-right info">
                    <p style="margin-right: 2%; margin-top: 2%;">{{ request.user.full_name }}</p>
                </div>
            </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">منو</li>
                <li class="active"><a href="{% url "institute:Home" %}">
                    <i class="fa fa-home"></i> <span>خانه</span>
                    <span class="pull-left-container">
                  <i class="fa pull-left"></i>
                </span>
                </a>
                </li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-institution"></i> <span>کلاس ها</span>
                        <span class="pull-left-container">
                            <i class="fa fa-angle-right pull-left"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active">
                            <a href="{% url 'institute:AddClass' %}">
                                <i class="fa fa-plus-circle"></i> <span>اضافه کردن کلاس</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>کاربران</span>
                        <span class="pull-left-container">
                            <i class="fa fa-angle-right pull-left"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active">
                            <a href="{% url "institute:InstituteClassUsers" %}">
                                <i class="fa fa-male"></i> <span>کاربران ثبت نام کرده</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="active">
                    <a href="{% url 'institute:logout' %}">
                        <i class="fa fa-sign-out"></i> <span>خروج</span>
                    </a>
                </li>


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
    {% block content %}

    {% endblock %}

    <footer class="main-footer text-left">
        <strong>Copyleft &copy; 2020 <a href="#">Zanjan University</a></strong>
    </footer>
</div>


<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<!-- InputMask -->
<script src="{% static 'plugins/input-mask/jquery.inputmask.js' %}"></script>
<script src="{% static 'plugins/input-mask/jquery.inputmask.date.extensions.js' %}"></script>
<script src="{% static 'plugins/input-mask/jquery.inputmask.extensions.js' %}"></script>
<!-- date-range-picker -->
<script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- bootstrap datepicker -->
<script src="{% static 'bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<!-- bootstrap color picker -->
<script src="{% static 'bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js' %}"></script>
<!-- bootstrap time picker -->
<script src="{% static 'plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>
<!-- SlimScroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- iCheck 1.0.1 -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static  'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static  'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static  'dist/js/demo.js' %}"></script>
<!-- babakhani datepicker -->
<script src="{% static  'dist/js/persian-date-0.1.8.min.js' %}"></script>
<script src="{% static  'dist/js/persian-datepicker-0.4.5.min.js' %}"></script>


{% block js %}

{% endblock %}


{% block script %}

{% endblock %}

</body>
</html>

templates/login_base.html
<!DOCTYPE html>
{% load static %}

<html lang="fa" dir="rtl">
<head>
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap-theme.css' %}">
    {#    <!-- Bootstrap rtl -->#}
    {#    <link rel="stylesheet" href="{% static 'dist/css/rtl.css' %}">#}
    {#    <!-- Font Awesome -->#}
    {#    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">#}
    {#    <!-- Ionicons -->#}
    {#    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">#}
    {#    <!-- Theme style -->#}
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.css' %}">


    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            background: #2c3e50; /*From http://flatuicolors.com/ */
        }

        .div_form {
            position: relative;
            width: 380px;
            height: max-content;
            margin: 10px auto;
            text-align: center;
            background: #ecf0f1;
            padding: 40px;
            -webkit-border-radius: 20px 0 0 0;
            -moz-border-radius: 20px 0 0 0;
            border-radius: 20px 0 0 0;
            -webkit-box-shadow: 0px 1px 0px #ad392d, inset 0px 1px 0px white;
            -moz-box-shadow: 0px 1px 0px #ad392d, inset 0px 1px 0px white;
            box-shadow: 0px 1px 0px #ad392d, inset 0px 1px 0px white;
            box-shadow: 20px 20px 20px;
        }

        h4 {
            font-size: 22px;
            margin-bottom: 25px;
            text-shadow: 1px 1px 0px white;
        }

        input {
            display: block;
            width: 300px;
            padding: 14px;
            -webkit-border-radius: 6px;
            -moz-border-radius: 6px;
            border-radius: 6px;
            border: 0;
            margin-bottom: 12px;
            color: #7f8c8d;
            font-size: 16px;
        }

        input:focus {
            background: #fafafa;
        }


        li {
            position: absolute;
            right: 40px;
            bottom: 62px;
            list-style: none;
        }

        a, a:visited {
            text-decoration: none;
            color: #7f8c8d;
            font-weight: 400;
            -webkit-transition: all .3s ease-in-out;
            -moz-transition: all .3s ease-in-out;
            transition: all .3s ease-in-out;
        }

        .login_button {
            position: relative;
            width: 110px;
            margin-top: 10px;
            background: #3498db;
            color: #fff;
            font-weight: 400;
            text-shadow: 1px 1px 0px #2d7baf;
            box-shadow: 0px 3px 0px #2d7baf;
            -webkit-transition: all .3s ease-in-out;
            -moz-transition: all .3s ease-in-out;
            transition: all .3s ease-in-out;
        }

        .register_button {
            position: relative;
            width: 120px;
            margin-top: 10px;
            background: #138f48;
            color: #ffffff;
            font-weight: 400;
            box-shadow: 0px 3px 0px #009140;
            -webkit-transition: all .3s ease-in-out;
            -moz-transition: all .3s ease-in-out;
            transition: all .3s ease-in-out;
            text-align: center;
            display: block;
            padding: 16px;
            -webkit-border-radius: 6px;
            -moz-border-radius: 6px;
            border-radius: 6px;
            border: 0;
            margin-bottom: 12px;
            font-size: 13px;
        }

        .register_btn {
            position: relative;
            width: 145px;
            background: #138f48;
            color: #ffffff;
            font-weight: 400;
            box-shadow: 0px 3px 0px #009140;
            -webkit-transition: all .3s ease-in-out;
            -moz-transition: all .3s ease-in-out;
            transition: all .3s ease-in-out;
            text-align: center;
            display: block;
            padding: 13px;
            -webkit-border-radius: 6px;
            -moz-border-radius: 6px;
            border-radius: 6px;
            border: 0;
            margin-bottom: 12px;
            font-size: 16px;
            margin-right: 27%;
            margin-top: 7%;
        }
    </style>
    {% block title %}
    {% endblock %}
</head>


{% include 'messages.html' %}
{% block body %}
{% endblock %}

</body>
</html>

templates/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <p style="margin-right:45px;">
            {{ message }}
        </p>
    </div>
{% endfor %}