institute/urls.py
from django.urls import path
from institute import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name=views.Home.name),
    path('add/', views.AddClass.as_view(), name=views.AddClass.name),
    path('register/', views.InstituteRegister.as_view(), name=views.InstituteRegister.name),
    path('edit/<int:pk>', views.EditClass.as_view(), name=views.EditClass.name),
    path('delete/<int:pk>', views.DeleteClass.as_view(), name=views.DeleteClass.name),
    path('users/', views.InstituteClassUsers.as_view(), name=views.InstituteClassUsers.name),
    path('logout/', views.Logout, name="logout"),


]

snappmusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls", namespace="users")),
    path('institute/', include("institute.urls", namespace="institute")),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name=views.Home.name),
    path('login/', views.Login.as_view(), name=views.Login.name),
    path('register/', views.UserRegister.as_view(), name=views.UserRegister.name),
    path('<int:pk>/', views.ViewInstitute.as_view(), name=views.ViewInstitute.name),
    path('class/<int:pk>', views.ViewClass.as_view(), name=views.ViewClass.name),
    path('class/register', views.RegisterClass.as_view(), name=views.RegisterClass.name),
    path('logout/', views.Logout, name="logout"),

]

institute/models.py
from django.db import models

# Create your models here.

institute/forms.py
from django import forms
from users import models


class AddInstituteClassForm(forms.ModelForm):
    class Meta:
        model = models.InstitutionClass
        fields = "__all__"


class EditInstituteClassForm(forms.ModelForm):
    class Meta:
        model = models.InstitutionClass
        fields = ['name', 'logo', 'teacher', 'instrument', 'time']


class RegisterInstitute(forms.ModelForm):
    password_2 = forms.CharField()

    class Meta:
        model = models.User
        fields = ['username', 'full_name', 'phone', 'description', 'address', 'logo', 'type']

institute/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib import messages
from institute.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from institute import forms
from users.models import User, InstitutionClass, UserClass


# Create your views here.

class Home(LoginRequiredMixin, View):
    name = "Home"
    template_name = "institute/home.html"

    def get(self, request):
        classes = InstitutionClass.objects.filter(user__username=request.user)
        context = {
            'classes': classes
        }
        return render(request, self.template_name, context)


class AddClass(LoginRequiredMixin, View):
    name = "AddClass"
    form = forms.AddInstituteClassForm
    template_name = "institute/add_class.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        user = User.objects.get(username=request.user)
        updated_request = request.POST.copy()
        updated_request.update({"user": user.id})
        post_form = self.form(updated_request, request.FILES)
        if post_form.is_valid():
            post_form.save()
        else:
            messages.error(request, "مشکلی پیش آمده است.")
            return render(request, self.template_name)
        messages.success(request, "کلاس با موفقیت اضافه شد")
        return redirect("institute:Home")


class EditClass(LoginRequiredMixin, UpdateView):
    model = InstitutionClass
    name = "EditClass"
    form_class = forms.EditInstituteClassForm
    template_name = "institute/edit_class.html"
    success_url = '/institute/'
    context_object_name = "class"


class DeleteClass(LoginRequiredMixin, DeleteView):
    model = InstitutionClass
    name = "DeleteClass"
    success_url = '/institute/'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class InstituteRegister(View):
    name = "InstituteRegister"
    template_name = "institute/institute_register.html"
    form = forms.RegisterInstitute

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        post_form = self.form(request.POST, request.FILES)
        if post_form.is_valid():
            password = request.POST.get("password")
            if password != post_form.cleaned_data.get("password_2"):
                messages.error(request, "رمز عبور با تکرار رمز عبور همخوانی ندارد.")
                return render(request, self.template_name)
            else:
                post_form.save()
                user = User.objects.get(username=post_form.cleaned_data.get('username'))
                user.set_password(password)
                user.save()
                login(request, user)
                messages.success(request, "اکانت شما با موفقیت ایجاد شد.")
                return redirect('institute:Home')
        else:
            print(post_form.errors)
            messages.error(request, "نام کاربری دیگری با این نام وجود دارد.")
        return render(request, self.template_name)


class InstituteClassUsers(LoginRequiredMixin, View):
    name = "InstituteClassUsers"
    template_name = "institute/institute_users.html"

    def get(self, request):
        institute_classes = InstitutionClass.objects.filter(user__username=request.user)
        users_classes = list()
        for institute_class in institute_classes:
            users = UserClass.objects.filter(user_class=institute_class)
            for usr in users:
                _dict = {
                    "username": usr.user.username,
                    "class_name": institute_class.name,
                    "class_teacher": institute_class.teacher,
                    "class_time": institute_class.time,
                }
                users_classes.append(_dict)
        context = {
            "user_classes": users_classes
        }
        return render(request, self.template_name, context)


def Logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('users:login')
    else:
        return redirect('users:login')

institute/templates/institute/add_class.html
{% extends 'institute_index.html' %}
{% load static %}
{% block css %}
    <style>
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            grid-gap: 20px;
            align-items: stretch;
        }

        .grid > article {
            border: 1px solid #ccc;
            box-shadow: 2px 2px 6px 0px rgba(0, 0, 0, 0.3);
        }

        .grid > article img {
            width: 100%;
            object-fit: contain;
            min-height: 220px;
            padding-right: 2%;
            padding-left: 2%;
            padding-top: 2%;
        }

        .grid .text {
            padding: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                اضافه کردن کلاس
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url "institute:Home" %}"><i class="fa fa-home"></i>خانه</a></li>
                <li><a href="{% url "institute:AddClass" %}"><i class="fa fa-plus-circle"></i>اضافه کردن کلاس</a></li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box box-success">
                            <div class="box-body with-border" id="canvas_div">
                                {% include 'messages.html' %}
                                <div class="row">
                                    <div class="col-md-10 col-md-push-1">
                                        <form method="post" enctype='multipart/form-data'>
                                            {% csrf_token %}
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>نام کلاس</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="name" type="text" class="form-control"
                                                               required placeholder="نام کلاس را وارد نمایید">
                                                    </div>

                                                </div>
                                                <div class="form-group">
                                                    <label>نام استاد</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="teacher" type="text" class="form-control"
                                                               required placeholder="نام استاد را وارد نمایید">
                                                    </div>

                                                </div>

                                                <div class="form-group">
                                                    <label>عکس کلاس</label>
                                                    <input name="logo" type="file" required>
                                                </div>

                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>ساز</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="instrument" type="text" class="form-control"
                                                               required placeholder="نام ساز را وارد نمایید">
                                                    </div>

                                                </div>
                                                <div class="form-group">
                                                    <label>تایم کلاس</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="time" type="text" class="form-control"
                                                               required placeholder="تایم کلاس را وارد نمایید">
                                                    </div>

                                                </div>



                                            </div>
                                            <div class="col-md-12" style="text-align: center">
                                                <button name="send" type="submit" class="btn btn-success">ایجاد</button>
                                            </div>


                                        </form>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- datepicker -->


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}
<!-- datepicker -->

institute/templates/institute/edit_class.html
{% extends 'institute_index.html' %}
{% load static %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                ویرایش {{ class.name }}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url "institute:Home" %}"><i class="fa fa-home"></i>خانه</a></li>
                <li><a href="{% url "institute:EditClass" class.id %}"><i class="fa fa-home"></i>ویرایش {{ class.name }}</a></li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box box-success">
                            <div class="box-body with-border" id="canvas_div">
                                {% include 'messages.html' %}
                                <div class="row">
                                    <div class="col-md-10 col-md-push-1">
                                        <form method="post" enctype='multipart/form-data'>
                                            {% csrf_token %}
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>نام کلاس</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="name" type="text" class="form-control"
                                                               placeholder="نام کلاس را وارد نمایید"
                                                               value="{{ class.name }}">
                                                    </div>

                                                </div>
                                                <div class="form-group">
                                                    <label>نام استاد</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="teacher" type="text" class="form-control"
                                                               placeholder="نام استاد را وارد نمایید"
                                                               value="{{ class.teacher }}">
                                                    </div>

                                                </div>

                                                <div class="form-group">
                                                    <label>عکس کلاس</label>

                                                    <img src="{{ class.logo.url }}" alt="Photo"
                                                         style="max-width: 98%;max-height: 98%;padding-right: 2%;
                                                         padding-top: 2%;">
                                                </div>

                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>ساز</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="instrument" type="text" class="form-control"
                                                               placeholder="نام ساز را وارد نمایید"
                                                               value="{{ class.instrument }}">
                                                    </div>

                                                </div>
                                                <div class="form-group">
                                                    <label>تایم کلاس</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-align-left">
                                                            </i>
                                                        </div>
                                                        <input name="time" type="text" class="form-control"
                                                               placeholder="تایم کلاس را وارد نمایید"
                                                               value="{{ class.time }}">
                                                    </div>

                                                </div>
                                                <div class="form-group">
                                                    <input name="logo" type="file">
                                                </div>


                                            </div>
                                            <div class="col-md-12" style="text-align: center">
                                                <button name="send" type="submit" class="btn btn-primary">
                                                    تغییرات اعمال شود
                                                </button>
                                            </div>


                                        </form>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- datepicker -->


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}
<!-- datepicker -->

institute/templates/institute/home.html
{% extends 'institute_index.html' %}
{% load static %}
{% block css %}
    <style>
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            grid-gap: 20px;
            align-items: stretch;
        }

        .grid > article {
            border: 1px solid #ccc;
            box-shadow: 2px 2px 6px 0px rgba(0, 0, 0, 0.3);
        }

        .grid > article img {
            width: 100%;
            object-fit: contain;
            min-height: 220px;
            padding-right: 2%;
            padding-left: 2%;
            padding-top: 2%;
        }

        .grid .text {
            padding: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                خانه
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url "institute:Home" %}"><i class="fa fa-home"></i>خانه</a></li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box box-success">
                            <div class="box-body with-border" id="canvas_div">
                                {% include 'messages.html' %}
                                {% include 'institute/institute_class_post.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- datepicker -->


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}
<!-- datepicker -->

institute/templates/institute/institute_class_post.html
<div class="container">
    <main class="grid">
        {% for class in classes %}
            <article>
                <img src="{{ class.logo.url }}" alt="Photo">
                <div class="text row">
                    <h3>{{ class.name }}</h3>
                    <p>{{ class.teacher }}</p>

                    <div class="col-md-6">
                        <a href="{% url "institute:EditClass" class.id %}"
                           class="btn btn-primary btn-block align-self-end">ویرایش</a>
                    </div>
                    <div class="col-md-6">
                        <a href="{% url "institute:DeleteClass" class.id %}"
                           class="btn btn-danger btn-block align-self-end"
                           onclick="return confirm('آیا از حذف این کلاس اطمینان دارید؟')">حذف</a>
                    </div>
                </div>

            </article>
        {% endfor %}
    </main>
</div>

institute/templates/institute/institute_register.html
\{% extends 'login_base.html' %}
{% load static %}

{% block title %}
    <title>پنل | ثبت نام آموزشگاه</title>
{% endblock %}


{% block body %}
    <div class="row div_form">

        <form enctype='multipart/form-data' method="post">
            {% csrf_token %}
            <img src="{% static 'dist/img/znu_logo.jpg' %}" alt="User Image"
                 style="height: 190px!important; text-align: center; position: relative; margin:20px;">
            <h4>SnappMusic</h4>
            <input type="text" name="type" value="1" style="display: none;"/>
            <label style="float: right" for="">
                نام کاربری: (برای مثال: test123 )
            </label>
            <input type="text" name="username" placeholder="نام کاربری آموزشگاه را وارد نمایید" id="username"
                   required/>
            <label style="float: right" for="">
                نام آموزشگاه: (برای مثال: پارس)
            </label>
            <input type="text" name="full_name" placeholder="نام آموزشگاه را وارد نمایید. برای مثال پارس"
                   id="full_name"
                   required/>
            <label style="float: right" for="">
                شماره تماس: (برای مثال: ۰۲۱۶۶۱۲۳۴۵۴)
            </label>
            <input type="text" name="phone" placeholder="شماره تماس آموزشگاه را وارد نمایید" id="phone" required/>
            <label style="float: right" for="">
                معرفی آموزشگاه:
            </label>
            <input type="text" name="description" placeholder="توضیحات جهت معرفی آموزشگاه" id="phone" required/>
            <label style="float: right" for="">
                آدرس آموزشگاه:
            </label>
            <input type="text" name="address" placeholder="آدرس آموزشگاه را وارد نمایید" id="phone" required/>
            <label style="float: right" for="">
                رمز عبور:
            </label>
            <input type="password" name="password" placeholder="رمز عبور خود را وارد نمایید" id="password"
                   required/>
            <label style="float: right" for="">
                تکرار رمز عبور:
            </label>
            <input type="password" name="password_2" placeholder="تکرار رمز عبور خود را وارد نمایید"
                   id="password_2"
                   required/>
            <label style="float: right">
                لوگو آموزشگاه
            </label>
            <input name="logo" type="file" required>
            <input class="register_btn" type="submit" value="ثبت نام" style="margin-left: 31%"/>

        </form>
    </div>
    <!-- jQuery 3 -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% endblock %}

institute/templates/institute/institute_users.html
{% extends 'institute_index.html' %}
{% load static %}
{% block css %}
    <style>
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            grid-gap: 20px;
            align-items: stretch;
        }

        .grid > article {
            border: 1px solid #ccc;
            box-shadow: 2px 2px 6px 0px rgba(0, 0, 0, 0.3);
        }

        .grid > article img {
            width: 100%;
            object-fit: contain;
            min-height: 220px;
            padding-right: 2%;
            padding-left: 2%;
            padding-top: 2%;
        }

        .grid .text {
            padding: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                لیست کاربران ثبت نام کرده
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url "institute:Home" %}"><i class="fa fa-home"></i>خانه</a></li>
                <li><a href="{% url "institute:InstituteClassUsers" %}"><i class="fa fa-male"></i>لیست کاربران ثبت نام
                    کرده</a></li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box box-success">
                            <div class="box-body with-border" id="canvas_div">
                                {% include 'messages.html' %}
                                <table id="example2" class="table table-bordered table-hover table-striped">
                                    <thead>
                                    <th width="25%" style="text-align: center">
                                        کاربر ثبت نام کرده
                                    </th>
                                    <th width="25%" style="text-align: center">
                                        نام کلاس
                                    </th>
                                    <th width="25%" style="text-align: center">
                                        استاد کلاس
                                    </th>
                                    <th width="25%" style="text-align: center">
                                        ساعت کلاس
                                    </th>
                                    </thead>
                                    <tbody>
                                    {% for user in user_classes %}
                                        <tr class="even pointer">
                                            <td class="a-center " style="text-align: center;">
                                                {{ user.username }}
                                            </td>
                                            <td class="a-center " style="text-align: center;">
                                                {{ user.class_name }}
                                            </td>
                                            <td class="a-center " style="text-align: center;">
                                                {{ user.class_teacher }}
                                            </td>
                                            <td class="a-center " style="text-align: center;">
                                                {{ user.class_time }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- datepicker -->


    <script src="{% static 'dist/js/jquery-flot-stack.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

{% endblock %}
<!-- datepicker -->